[pytest]
addopts =
    --base-url=https://the-internet.herokuapp.com
    --browser chromium
    --browser firefox
    --browser webkit
    --video=retain-on-failure
    --screenshot=only-on-failure
    --tracing=on
    --slowmo=200
    --html=report/index.html --self-contained-html
    -n auto
    --dist=loadscope
    -vv
    --junitxml=report/pytest-junit.xml
    --cov=.
    --cov-report=xml
    --reruns 2
    

testpaths =
    tests
python_files =
    test_*.py
generate_report_on_test = 
    True
    