[pytest]
addopts =
    --headed
    --browser chromium
    --browser firefox
    --browser webkit
    --video=retain-on-failure
    --screenshot=only-on-failure
    --tracing=retain-on-failure
    --slowmo=200
    -n auto

testpaths =
    tests
python_files =
    test_*.py