[pytest]
addopts =
    --browser chromium
    --browser firefox
    --browser webkit
    --video=retain-on-failure
    --screenshot=only-on-failure
    --tracing=retain-on-failure
    --slowmo=200
    --html=report/index.html --self-contained-html
    -n auto
    --dist=loadscope
    -vv
    

testpaths =
    tests
python_files =
    test_*.py