sonar.projectKey=jardevson
sonar.projectName=PlaywrightPython
sonar.organization=JarDeVSon_PlaywrightPython
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=report/pytest-junit.xml